### ISSUE TITLE
remove es6-imports from lib

### ISSUE THREAD

**Issue by Xiphe** [zackify/react-use-upload#1]
The version currently published to npm still uses es6-import syntax. 
Since most of the time a module bundler or test framework will not transpile node_modules. This leads to errors in environments that do not understand es6 imports.

In my case I would need to add custom jest transform just for this module.

I would propose to publish this module using commonJS + interop.

**Comment by zackify** [comment]
It uses es6 modules because this is the only way webpack can treeshake. https://webpack.js.org/guides/tree-shaking/#conclusion

Are you not able to use a more up to date bundled that supports es modules? I am totally open to adding a commonjs build though. Just wanted to point out that using the current build is the most performant

**Comment by zackify** [comment]
I wish jest supported it out of the box... I will work on this soon or would take a pr as well

**Comment by zackify** [comment]
Ideally i think it should be on the users end to transpile ES6 down to es5 if that is needed. But I have added a cjs build to `react-use-upload/cjs` import from there to have that build. 

I kept the main export using es6, because bundlers support it and is the future.

Install @0.5.1

**Comment by Xiphe** [comment]
Hey @zackify.

Thanks for the fast solution and making your reasoning clear.

I agree that supporting tree-shaking is a big win. But it seems odd to me that this library is the only one that requires custom treatment when being used in node (SSR/testing).

Since tree-shaking has most value in browsers and node does not support es6 modules yet, I would propose to move the current `main` to [`browser`](https://github.com/defunctzombie/package-browser-field-spec) and have the cjs entry as `main`.

**Comment by zackify** [comment]
Okay, I think i have it setup correct. Can you try 0.5.2?

**Comment by Xiphe** [comment]
Yes, works like a charm. My parcel bundle uses the source from `lib` while jest tests work without any additional configuration. Thanks a lot!

**Comment by zackify** [comment]
Thanks for using my library and helping me learn to setup the build better :) in the past I did only common js so I haven’t set those fields in the package before! Let me know if you need anything else.
