### ISSUE TITLE
useUpload should accept FileOrFileList | null | undefined

### ISSUE THREAD

**Issue by audiolion** [zackify/react-use-upload#11]
Hey, was using your library today with TypeScript and the first argument to `useUpload` requires a `FileOrFileList` type, but does not accept null / undefined. I don't have the file yet when the component first mounts. I noticed that you check for files being null / undefined, so I think the type is wrong and needs to be updated to include null / undefined.

https://github.com/zackify/react-use-upload/blob/2d57e7da7dae7eb88789f400119180eda39cae8b/src/use-upload.tsx#L43-L52

![image](https://user-images.githubusercontent.com/2430381/87858939-9af22e80-c8ff-11ea-96d1-ce7e7d873cd4.png)

**Comment by zackify** [comment]
Sounds good, you can make a PR or I will try to get to it this week. really want to refactor this library too... The api surface could be simpler now that I know hooks and TS better. I actually need to use this myself next week

**Comment by zackify** [comment]
Fixed in the latest version, the library always requires a FileList for simplicity, even if you want to upload a single file
